### ISSUE TITLE
Update-ServicePackageFiles: first *.exe in code-directory is used to update package.xml

### ISSUE THREAD

**Issue by JohannesDrexler** [Azure/SFNuGet#3]
The function 'Update-ServicePackageFiles' uses following code to select the main-exe of the ServiceFabric-Application.

`$execFile = Get-ChildItem $path\Code *.exe | Select-Object -First 1`

Code ends up using wrong assemblies to update the Package.xml....

The function has a parameter $svcManifestFile which contains the name of the exe that is supposed to be used. Why not read from the ServiceManifest.xml ?

**Comment by Haishi2016** [comment]
Hi @JohannesDrexler: Thank you for your report. I've just checked in a fix as per suggested.

**Comment by JohannesDrexler** [comment]
Thank you very much for checking this. I have tested your fix and it works for me.
