### ISSUE TITLE
Suggestion: Nuget-Properties: use assemblyTitle in packageName and as id

### ISSUE THREAD

**Issue by JohannesDrexler** [Azure/SFNuGet#5]
I have a suggestion about the nugetpackage that is being created.
Currently the assemblyTitle is used as Title in the nuspec but the Id of the package is the packageName as configured in "ServiceManifest.xml". This name is also used as name of the packge.

My suggestion is to use the assemblyTitle in this 2 places as well. Doesn't this make more sense ?

**Comment by Haishi2016** [comment]
This can be customized by changing the Package.xml file, which is under the PowerShell module folder. The file contains a few placeholder variables that are dynamically replaced, such as $assemblyTitle, $serviceName. You can change the id of the package to $assemblyTitle, though I think $serviceName from the service manifest is still a good default.

**Comment by Haishi2016** [comment]
I'm closing this for now.
