### ISSUE TITLE
Support for setting the nupkg version

### ISSUE THREAD

**Issue by MedAnd** [Azure/SFNuGet#6]
I would like to set the nupkg version. I attempted by modifying:

1. ServiceManifestVersion field in ApplicationManifest.xml
2. Version field in ServiceManifest.xml

Neither of the above worked, debugged the power-shell and wondering if this is supported?

**Comment by Haishi2016** [comment]
That can be set in Package.xml.

**Comment by MedAnd** [comment]
Not sure if this is meant to work but I set the Package version as per below, recompiled in Release mode, re-packaged and finally used SFNuGet however the package created was still at version 1.0.0... 

My Service Fabric microservice project is in .Net Core  *.csproj, along with the values used for nuspec. 
Looking through the release\bin folder I cannot seem to locate any Package.xml file... ?

![image](https://user-images.githubusercontent.com/13365135/33664501-f5cb61c2-dae7-11e7-87bc-32c67f8f2725.png)

**Comment by Haishi2016** [comment]
Package.xml comes with the PowerShell module (under the same folder where the PowerShell module is). It has several placeholder variables (marked with "$") that are dynamically replaced during package, including version. If you put a new version in the file it will be taken.

**Comment by MedAnd** [comment]
Hi @Haishi2016, I think I finally found the file, it's inside SFNuGet\PowerShell folder? Will try making the above changes but wanted to ask what you thought of:

1. adding support for using the Package version from the csproj file
or
2. adding support for using the Version from the ServiceManifest.xml file

**Comment by Haishi2016** [comment]
1. will be hard as the tool works against a package folder, not the solution/project folder.
2. is already supported. Use $serviceVersion as placeholder for service version from ServiceManifest.xml file.
