### ISSUE TITLE
Support for packaging Guest Executables

### ISSUE THREAD

**Issue by MedAnd** [Azure/SFNuGet#9]
I would like to package Guest Executables as nugets. I attempted to package the following project [Minio.ServiceFabric](https://github.com/MedAnd/Minio.ServiceFabric) but encountered exceptions.

**Comment by NickDarvey** [comment]
@MedAnd what exception are you getting? Can you share it here?

**Comment by MedAnd** [comment]
Hi @NickDarvey, seems the code is expecting to find a file or assembly whereas I am using a .bat file to launch the minio.exe process...

New-ServiceFabricNuGetPackage : Exception calling "LoadFrom" with "1" argument(s): "Could not load file or assembly
'file:///C:\Users\Admin\AppData\Local\Temp\SFNuGet\feccfaee-7b73-4954-be36-79e942568261\Code\minio_gateway_azure.bat'
or one of its dependencies. The module was expected to contain an assembly manifest."
At line:1 char:1
 New-ServiceFabricNuGetPackage -InputPath E:\Projects\ServiceFabric.Mi ...
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-ServiceFabricNuGetPackage], MethodInvocationException
    + FullyQualifiedErrorId : BadImageFormatException,New-ServiceFabricNuGetPackage

**Comment by MedAnd** [comment]
I should have changed the title to support for SF process (host) targets other than exes...

**Comment by Haishi2016** [comment]
@MedAnd  What do you mean. The fix didn't work for you?

**Comment by MedAnd** [comment]
Oops @Haishi2016... I did not see the commit :blush: I just tested and can confirm it's working... brilliant!
The minio.exe which was 23mb has even been compressed/packaged into a 8mb SFNuget! 

I guess I have some work to do to update the [Minio.ServiceFabric](https://github.com/MedAnd/Minio.ServiceFabric) project.

**Comment by Haishi2016** [comment]
Thank you @MedAnd. Please let me know when you are done with your project update. I'd like to share the project with the SF team.

**Comment by MedAnd** [comment]
@Haishi2016  [Minio.ServiceFabric](https://www.nuget.org/packages/Minio.ServiceFabric/1.0.0) is now live on nuget.org. Let me know what you think...
